name: Publish github pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
    ghpages:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.1
        - name: Set up Python
          uses: actions/setup-python@v5.0.0
          with:
            python-version: 3.11
        - name: Deploy to github pages
          run: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install -r requirements.txt
            mkdocs gh-deploy --force --clean --verbose
